#pragma once

#ifndef CELLTAP_NAMESPACE_H
#define CELLTAP_NAMESPACE_H 1

#define USING_CELLTAP_NAMESPACE

#ifdef USING_CELLTAP_NAMESPACE
#define CELLTAP_NAMESPACE					CellTap_Namespace
#define CELLTAP_NAMESPACE_BEGIN				namespace CELLTAP_NAMESPACE{
#define CELLTAP_NAMESPACE_END				}
#define CELLTAP_FORWARD_DECLARE(X)			namespace CELLTAP_NAMESPACE{class X;}
#define CELLTAP_PREPEND_NAMESPACE(X)		CELLTAP_NAMESPACE::X
#define USING_NAMESPACE_CELLTAP				using namespace CELLTAP_NAMESPACE;
#else
#define CELLTAP_NAMESPACE					
#define CELLTAP_NAMESPACE_BEGIN				
#define CELLTAP_NAMESPACE_END				
#define CELLTAP_FORWARD_DECLARE(X)			class X;
#define CELLTAP_PREPEND_NAMESPACE(X)		X
#define USING_NAMESPACE_CELLTAP				
#endif

#endif //CELLTAP_NAMESPACE_H